ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1

network={
        ssid="iPhone"
	psk="Valeria26"
	priority=5
}

network={
	ssid="Reds"
	psk="Tantan20"
	priority=10
}

network={
	ssid="GA14Mauro"
	psk="koshka04"
	priority=1
}
