# Capa propia del proyecto: robot aspiradora RumBa (CE-1113)

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "robot"
BBFILE_PATTERN_robot = "^${LAYERDIR}/"

# Prioridad mayor que meta-oe (5) y meta-raspberrypi (9) para que
# nuestros .bbappend siempre ganen.
BBFILE_PRIORITY_robot = "12"

LAYERDEPENDS_robot = "core openembedded-layer"
LAYERSERIES_COMPAT_robot = "scarthgap"
